Docker
B3r3z/My_Chess_game pull request #1
Opened 2022-10-23 13:03 UTC by B3r3z

2022-10-23 13:14 UTC, kecajjo requested changes
Create proper folder structure and mentioned in the comments, will help later on
you can also add some README.md and license (MIT for example)

2022-10-23 13:14 UTC, kecajjo commented on DockerRun.sh
> +#! /bin/bash
finish this script before merging and move it to docker folder

2022-10-23 13:14 UTC, kecajjo commented on CMakeLists.txt
> +)
Move this file to src folder

2022-10-23 13:14 UTC, kecajjo commented on run.sh
> +make
move file to src folder

2022-10-23 13:14 UTC, kecajjo commented on Dockerfile
> +ENTRYPOINT [ "/bin/bash", "-c" ]
Create docker folder and move file to it

2022-10-31 10:23 UTC, B3r3z commented on DockerRun.sh
> +#! /bin/bash
ok

2022-10-31 10:24 UTC, B3r3z commented on CMakeLists.txt
> +)
fixed

2022-10-31 10:24 UTC, B3r3z commented on run.sh
> +make
fixed

2022-10-31 10:31 UTC, B3r3z commented on Dockerfile
> +ENTRYPOINT [ "/bin/bash", "-c" ]
fixed

2022-10-31 10:47 UTC, kecajjo commented on DockerRun.sh
> +#! /bin/bash
done

2022-10-31 10:48 UTC, kecajjo approved these changes

2022-10-31 10:49 UTC, merged